// Calendar
export const SAVE_PERIOD = 'SAVE_PERIOD'
export const SET_SELECTED_DAY = 'SET_SELECTED_DAY'

// Service
export const ADD_EXAM_NOTE = 'ADD_EXAM_NOTE'
export const ADD_TASK_NOTE = 'ADD_TASK_NOTE'
export const ADD_OTHER_NOTE = 'ADD_OTHER_NOTE'
export const GET_NOTE_ERROR = 'NOTE_ERROR'
export const LOAD_EXAM_NOTES = 'LOAD_EXAM_NOTES'
export const LOAD_TASK_NOTES = 'LOAD_TASK_NOTES'
export const LOAD_OTHER_NOTES = 'LOAD_OTHER_NOTES'
export const LOAD_ALL_SHEETS = 'LOAD_ALL_SHEETS'
export const RESET_SHEETS_UPDATED = 'RESET_SHEETS_UPDATED'

// Sheet
export const GET_CURRENT_NOTE = 'GET_CURRENT_NOTE'
export const SHOW_SHEET_FORM = 'SHOW_SHEET_FORM'
export const SHOW_NEW_NOTE = 'SHOW_NEW_NOTE'

// Alert
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

// Auth
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'
export const LOGOUT = 'LOGOUT'

// Loading
export const LOADING = 'LOADING'